site_name: KGTK documentation
nav:
  - Home: index.md
  - Getting started: install.md
  - KGTK file specification: specification.md
  - 'Import commands':
      - 'import-atomic': 'import/import_atomic.md'
      - 'import-conceptnet': 'import/import_conceptnet.md'
      - 'import-concept-pairs': 'import/import_concept_pairs.md'
      - 'import-framenet': 'import/import_framenet.md'
      - 'import-ntriples': 'import/import_ntriples.md'
      - 'import-visualgenome': 'import/import_visualgenome.md'
      - 'import-wikidata': 'import/import_wikidata.md'
      - 'import-wordnet': 'import/import_wordnet.md'
  - 'Export commands':
      - 'export-gt': 'export/export_gt.md'
      - 'generate_wikidata_triples': 'export/generate_wikidata_triples.md'
  - 'Transformation commands':
      - 'add-id': 'transform/add_id.md'
      - 'calc': 'transform/calc.md'
      - 'cat': 'transform/cat.md'
      - 'compact': 'transform/compact.md'
      - 'expand': 'transform/expand.md'
      - 'explode': 'transform/explode.md'
      - 'filter': 'transform/filter.md'
      - 'ifempty': 'transform/ifempty.md'
      - 'ifexists': 'transform/ifexists.md'
      - 'ifnotempty': 'transform/ifnotempty.md'
      - 'ifnotexists': 'transform/ifnotexists.md'
      - 'implode': 'transform/implode.md'
      - 'join': 'transform/join.md'
      - 'lift': 'transform/lift.md'
      - 'md': 'transform/md.md'
      - 'query': 'transform/query.md'
      - 'remove-columns': 'transform/remove_columns.md'
      - 'rename-columns': 'transform/rename_columns.md'
      - 'reorder-columns': 'transform/reorder_columns.md'
      - 'sort': 'transform/sort.md'
      - 'unique': 'transform/unique.md'
      - 'unreify-rdf-statements': 'transform/unreify_rdf_statements.md'
      - 'unreify-values': 'transform/unreify_values.md'
      - 'zconcat': 'transform/zconcat.md'
  - 'Curation commands':
      - 'clean-data': 'curate/clean_data.md'
      - 'validate': 'curate/validate.md'
  - 'Analysis commands':
      - 'connected-components': 'analysis/connected_components.md'
      - 'graph-embeddings': 'analysis/graph_embeddings.md'         
      - 'graph-statistics': 'analysis/graph_statistics.md'
      - 'paths': 'analysis/paths.md'
      - 'reachable-nodes': 'analysis/reachable_nodes.md'
      - 'text-embeddings': 'analysis/text_embedding.md'

theme:
  name: material
  logo: images/kgtk_logo_200x200.png
extra_css:
  - stylesheets/extra.css
repo_url: https://github.com/usc-isi-i2/kgtk

plugins:
  - mknotebooks

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
